---
- name: Create GitLab SSL configuration folder.
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_create_self_signed_cert
  notify:
  - reconfigure gitlab

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}"
    -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: gitlab_create_self_signed_cert
  notify:
  - reconfigure gitlab

- name: set url
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "nginx\\['redirect_http_to_https'\\]"
    line: "nginx['redirect_http_to_https'] = true"
    backrefs: yes
  notify:
  - reconfigure gitlab
