concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "devops"
  url = "https://gitlab.devops.davar.com/"
  token = "3f2gjUryD7_PZyws5TTD"
  tls-ca-file = "/etc/gitlab/ssl/gitlab.devops.davar.com.crt"
  tls-key-file = "/etc/gitlab/ssl/gitlab.devops.davar.com.key"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.12"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    pull_policy = ["always"]
    shm_size = 268435456
    extra_hosts = ["gitlab.devops.davar.com:192.168.1.99"]
